@startuml
left to right direction

actor "Użytkownik" as User
actor "Administrator Systemu" as Admin

package "Przypadki użycia" {
    usecase "Zakup biletu" as UC_Bilet
    usecase "Zdalne zarządzanie oprogramowaniem\nbiletomatu" as UC_Zarządzanie
}

User --> UC_Bilet
Admin --> UC_Zarządzanie

@enduml
