@startuml 

left to right direction

actor "Użytkownik" as User
actor "Administrator Systemu" as Admin

package "Przypadku użycia" {
usecase "Wyświetlenie listy raportów" as UC1
usecase "Konfiguracja oferty biletomatu" as UC2
usecase "Wyświetlenie oferty biletomatu" as UC3
usecase "Wybór języka" as UC4
}

Admin -> UC1
User -> UC3
Admin -> UC2
User -> UC4

@enduml
